In [19]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

import pickle

In [20]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [21]:
df.drop("customerID", axis=1, inplace=True)
y = df["Churn"].map({"Yes": 1, "No": 0})
X = df.drop("Churn", axis=1)


In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [24]:
def engineer(df):
    df = df.copy()

    bins = [0,12,24,36,48,60,72]
    labels = ["0-1yr","1-2yr","2-3yr","3-4yr","4-5yr","5+yr"]

    df["tenure_group"] = pd.cut(df["tenure"], bins=bins, labels=labels)

    df["HighRisk_Contract"] = (df["Contract"] == "Month-to-month").astype(int)

    df["NoSupport"] = (
        (df["TechSupport"] == "No") &
        (df["OnlineSecurity"] == "No")
    ).astype(int)

    df["FiberUser"] = (df["InternetService"] == "Fiber optic").astype(int)

    return df

X_train = engineer(X_train)
X_test = engineer(X_test)


In [25]:
num_cols = ["tenure", "MonthlyCharges"]

cat_cols = X_train.select_dtypes(include=["object", "category","string"]).columns

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
])
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

In [ ]:
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced"
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        max_depth=10,
        min_samples_split=5,
        class_weight="balanced",
        random_state=42
    ),
    "XGBoost": XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_pos_weight,
        random_state=42,
        eval_metric="logloss"
    )
}

In [28]:
results = []
for name, model in models.items():
    print("\n\n")
    print(f"Training: {name}")
    pipeline = Pipeline([
        ("preprocess", preprocessor),
        ("model", model)
    ])
    cv_score = cross_val_score(
        pipeline, X_train, y_train,
        cv=5, scoring="roc_auc"
    ).mean()
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)
    y_prob = pipeline.predict_proba(X_test)[:, 1]
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)
    cm = confusion_matrix(y_test, y_pred)
    print(f"CV ROC-AUC : {cv_score:.4f}")
    print(f"Accuracy   : {acc:.4f}")
    print(f"Precision  : {prec:.4f}")
    print(f"Recall     : {rec:.4f}")
    print(f"F1 Score   : {f1:.4f}")
    print(f"ROC-AUC    : {auc:.4f}")
    print("Confusion Matrix:\n", cm)
    results.append({
        "CV": cv_score,
        "Model": name,
        "ROC-AUC": auc,
        "F1": f1,
        "Recall": rec,
        "Pipeline": pipeline
    })




Training: Logistic Regression
CV ROC-AUC : 0.8483
Accuracy   : 0.7509
Precision  : 0.5213
Recall     : 0.7540
F1 Score   : 0.6164
ROC-AUC    : 0.8412
Confusion Matrix:
 [[776 259]
 [ 92 282]]



Training: Random Forest
CV ROC-AUC : 0.8357
Accuracy   : 0.7268
Precision  : 0.4910
Recall     : 0.8048
F1 Score   : 0.6099
ROC-AUC    : 0.8244
Confusion Matrix:
 [[723 312]
 [ 73 301]]



Training: XGBoost
CV ROC-AUC : 0.8420
Accuracy   : 0.7502
Precision  : 0.5196
Recall     : 0.7781
F1 Score   : 0.6231
ROC-AUC    : 0.8406
Confusion Matrix:
 [[766 269]
 [ 83 291]]


In [30]:
for r in results:
    r["Score"] = (
        0.45 * r["Recall"] +
        0.25 * r["F1"] +
        0.20 * r["ROC-AUC"] +
        0.10 * r["CV"]
    )

results = sorted(results, key=lambda x: x["Score"], reverse=True)
best_model = results[0]

for r in results:
    print(
        f"{r['Model']} → Score: {r['Score']:.4f}, "
        f"Recall: {r['Recall']:.4f}, "
        f"F1: {r['F1']:.4f}, "
        f"AUC: {r['ROC-AUC']:.4f}, "
        f"CV: {r['CV']:.4f}"
    )

print("\nBEST MODEL:", best_model["Model"])

Random Forest → Score: 0.7631, Recall: 0.8048, F1: 0.6099, AUC: 0.8244, CV: 0.8357
XGBoost → Score: 0.7582, Recall: 0.7781, F1: 0.6231, AUC: 0.8406, CV: 0.8420
Logistic Regression → Score: 0.7465, Recall: 0.7540, F1: 0.6164, AUC: 0.8412, CV: 0.8483

BEST MODEL: Random Forest


In [17]:
pickle.dump(best_model["Pipeline"], open("model.sav", "wb"))
print("\nModel Saved")


Model Saved
